# Generated by Django 3.1.12 on 2022-02-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
